// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hosts} from '../models';
import {configs} from '../models';

export function AddHost(arg1:hosts.HostItem):Promise<void>;

export function GetAppName():Promise<string>;

export function GetChannel():Promise<string>;

export function GetConfig():Promise<configs.Config>;

export function GetHosts():Promise<Array<hosts.HostItem>>;

export function GetRepoUrl():Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveConfig(arg1:configs.Config):Promise<void>;
