// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1) {
  return window['go']['main']['App']['AddHost'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function GetAppName() {
  return window['go']['main']['App']['GetAppName']();
}

export function GetChannel() {
  return window['go']['main']['App']['GetChannel']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function GetRepoUrl() {
  return window['go']['main']['App']['GetRepoUrl']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
